(function(w){"use strict";if(!(/iPhone|iPad|iPod/.test(navigator.platform)&&navigator.userAgent.indexOf("AppleWebKit")>-1)){return;}
var doc=w.document;if(!doc.querySelector){return;}
var meta=doc.querySelector("meta[name=viewport]"),initialContent=meta&&meta.getAttribute("content"),disabledZoom=initialContent+",maximum-scale=1",enabledZoom=initialContent+",maximum-scale=10",enabled=true,x,y,z,aig;if(!meta){return;}
function restoreZoom(){meta.setAttribute("content",enabledZoom);enabled=true;}
function disableZoom(){meta.setAttribute("content",disabledZoom);enabled=false;}
function checkTilt(e){aig=e.accelerationIncludingGravity;x=Math.abs(aig.x);y=Math.abs(aig.y);z=Math.abs(aig.z);if(!w.orientation&&(x>7||((z>6&&y<8||z<8&&y>6)&&x>5))){if(enabled){disableZoom();}}
else if(!enabled){restoreZoom();}}
w.addEventListener("orientationchange",restoreZoom,false);w.addEventListener("devicemotion",checkTilt,false);})(this);(function($){"use strict";$(document).ready(function(){(function($){$(window).resize(function(){var $windowWidth=$(window).width();});var $container=$('#portfolio-container');$container.imagesLoaded(function(){$container.isotope({layoutMode:'fitRows',animationEngine:'best-available',animationOptions:{queue:false,duration:800}});});$('#portfolio-filter a').on('click',function(e){$('.active').removeClass('active');$(this).parent().addClass('active');var selector=$(this).attr('data-filter');$('#portfolio-container .isotope-item a.portfolio-zoom').attr('rel','prettyPhoto[gallery]');$('#portfolio-container '+selector+' a.portfolio-zoom').attr('rel','prettyPhoto[active]');$container.isotope({filter:selector,layoutMode:'fitRows'});e.preventDefault();});var $optionSets=$('#filter li'),$optionLinks=$optionSets.find('a');$optionLinks.on('click',function(e){var $this=$(this);if($this.hasClass('selected')){e.preventDefault();}
var $optionSet=$this.parents('#filtrable');$optionSet.find('.selected').removeClass('selected');$this.addClass('selected');var options={},key=$optionSet.attr('data-option-key'),value=$this.attr('data-option-value');value=value==='false'?false:value;options[key]=value;if(key==='layoutMode'&&typeof changeLayoutMode==='function'){changeLayoutMode($this,options)}else{$container.isotope(options);}
e.preventDefault();});})(jQuery);$(window).resize();});})(jQuery);(function($){"use strict";$(document).ready(function(){if(jQuery().prettyPhoto){jQuery("a[rel^='prettyPhoto']").prettyPhoto({deeplinking:false,theme:'facebook'});}});})(jQuery);(function($){"use strict";$(document).ready(function(){$(".tabs").tabs({fx:{opacity:'toggle'}});$(function(){$(".toggle_container").hide();$("p.trigger").live('click',function(){$(this).toggleClass("active").next().slideToggle("normal");return false;});});});})(jQuery);(function($){"use strict";jQuery(document).ready(function($){var $mobileNavButton=$('#mobile-nav-button');var $navigationUL=$('#main-nav-wrapper');$mobileNavButton.click(function(){$navigationUL.slideToggle();$mobileNavButton.toggleClass('active');});$navigationUL.find('a').click(function(){if($mobileNavButton.css('display')=='block'){$navigationUL.slideToggle();$mobileNavButton.toggleClass('active');}});});})(jQuery);(function($){"use strict";$(document).ready(function(){function testAnim(x){$('#animateTest').removeClass().addClass(x+' animated');var wait=window.setTimeout(function(){$('#animateTest').removeClass()},1300);}
$('a[data-test]').click(function(e){e.preventDefault();var anim=$(this).attr('data-test');testAnim(anim);});function inView(elem){var $elem=$(elem);if($elem.length>0){var scrollElem=((navigator.userAgent.toLowerCase().indexOf('webkit')!=-1)?'body':'html');var viewportTop=$(scrollElem).scrollTop();var viewportBottom=viewportTop+$(window).height();var elemTop=Math.round($elem.offset().top);var elemBottom=elemTop+$elem.height();return((elemTop<viewportBottom)&&(elemBottom>viewportTop));}
else{return false;}}
function startAnimation(){var $elem=$('.luxe-animate');$elem.each(function(){if($(this).hasClass('animated'))return;if(inView($(this))){var animation=$(this).data('animation');$(this).addClass('animated '+animation);}});}
function startChart(){var $elem=$('.chart');if($elem.hasClass('animated'))return;if(inView($elem)){$elem.easyPieChart({trackColor:'#343434',scaleColor:false,scaleLength:false,lineCap:'butt',lineWidth:10,size:130,rotate:0,animate:2000,onStep:function(from,to,percent){jQuery(this.el).find('.chart-percent').text(Math.round(percent));}});$elem.addClass('animated');}}
function startProgress(){var $elem=$('.progress-bar');if($elem.hasClass('stretchRight'))return;if(inView($elem)){$elem.addClass('stretchRight');}}
$(window).load(function(){if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){$(window).scroll(function(){startChart();});startChart();var $elem=$('.luxe-animate');$elem.css('visibility','visible');}
else{$(window).scroll(function(){startAnimation();startChart();startProgress();});setTimeout(function(){startAnimation();startProgress();},2000);startChart();}});});})(jQuery);(function($){"use strict";jQuery("a.luxe-post-like").click(function(event){event.preventDefault();var heart=jQuery(this);var post_id=heart.data("post_id");jQuery.ajax({type:"post",url:ajax_var.url,data:"action=luxe-post-like&nonce="+ajax_var.nonce+"&luxe_post_like=&post_id="+post_id,success:function(count){if(count.indexOf("already")!==-1)
{var lecount=count.replace("already","");if(lecount==0)
{var lecount="Like";}}
else
{heart.children(".like").addClass("pastliked").removeClass("disliked").html("<i class='fa fa-heart'></i>");heart.children(".count").addClass("liked").removeClass("disliked").text(count);}}});})})(jQuery);(function($){"use strict";$(document).ready(function(){fixFlexsliderHeight();});$(window).load(function(){fixFlexsliderHeight();});$(window).resize(function(){fixFlexsliderHeight();});function fixFlexsliderHeight(){$('.vertical-slider').each(function(){var sliderHeight=0;$(this).find('.slides > li').each(function(){var slideHeight=$(this).height();if(sliderHeight<slideHeight){sliderHeight=slideHeight;}});$(this).find('ul.slides').css({'height':sliderHeight});$(this).find('ul.slides li').css({'height':sliderHeight});});}
$(window).load(function(){var $luxeFlexSliders=$('.luxe-flexslider-gallery');$luxeFlexSliders.flexslider({animation:"slide",prevText:"",nextText:"",before:function(slider){slider.find('.flex-viewport').css('width',parseInt(slider.width()));}});$(window).resize(function(){$luxeFlexSliders.each(function(){$(this).find('.flex-viewport').css('width',parseInt($(this).width()));});});});})(jQuery);(function($){"use strict";$(window).load(function(){var $luxeVerticalSliders=$('.vertical-slider');$luxeVerticalSliders.flexslider({animation:"slide",direction:"vertical",prevText:"",nextText:"",slideshow:true,slideshowSpeed:3000,animationSpeed:600,animationLoop:true,});});})(jQuery);(function($){"use strict";$(window).load(function(){$('#testimonial-carousel-nav').flexslider({animation:"slide",controlNav:false,animationLoop:false,slideshow:false,itemWidth:110,itemMargin:20,asNavFor:'#testimonial-carousel',start:function(slider){if(slider.pagingCount===1)slider.addClass('flex-centered');}});$('#testimonial-carousel').flexslider({animation:"slide",controlNav:false,animationLoop:false,slideshow:false,sync:"#testimonial-carousel-nav"});});})(jQuery);(function($){"use strict";jQuery(".team-carousel, .posts-carousel").owlCarousel({navigation:true,navigationText:false,pagination:false,items:3,theme:'glissando'});jQuery(".client-carousel").owlCarousel({navigation:true,navigationText:false,pagination:false,items:5,theme:'glissando'});})(jQuery);